server <- function(input, output, session) {
  output$main_ui <- renderUI({
    switch(
      input$chat_mode,
      "guidance" = tagList(
        bslib::card(
          style = "max-height: 85vh; overflow-y: auto;",

          bslib::card_body(
            shinychat::chat_ui(
              id = "chat",
              messages = "Hey hey hey! I will search available guidance from the Analysts' Guide and Statistics HoP Hub to provide the answers to your questions. How can I help?",
              icon_assistant = img(
                src = "guidance-frederick.png",
                style = "height:30px; width:auto;"
              ),
              width = "min(980px, 100%)"
            ),

            fill = TRUE,
            min_height = "400px"
          ),
          bslib::card_footer(
            tagList(
              div(
                style = "background-color: #f8f9fa; border-left: 4px solid #0072B2; padding: 12px;",
                strong("Note:"),
                "Responses are generated by AI based on the Analysts' Guide and HoP hub materials. Please verify any answers using the",
                tags$a(
                  href = "https://rsconnect/rsc/hop-guidance/",
                  "HoP Hub",
                  target = "_blank"
                ),
                "or the",
                tags$a(
                  href = "https://dfe-analytical-services.github.io/analysts-guide/",
                  "Analysts' Guide",
                  target = "_blank"
                ),
                "websites."
              ),
              div(
                style = "background-color: #f8f9fa; border-left: 4px solid #0072B2; padding: 12px; margin-bottom: 16px;",
                strong("Note:"),
                "This is just a prototype, please send any feedback to ",
                tags$a(
                  href = "mailto:cameron.race@education.gov.uk",
                  "cameron.race@education.gov.uk"
                ),
                "with the subject line 'Ask Frederick' to help us make this better!"
              ),
              actionButton(
                "reset_chat",
                "Reset Chat",
                style = "width: 100%; margin-top: 8px;"
              )
            )
          )
        )
      ),
      "data_interrogator" = tagList(
        fileInput("csv_upload", "Upload CSV file"),
        textInput("data_question", "Ask about your data:", ""),
        actionButton("data_submit", "Ask"),
        conditionalPanel(
          condition = "input.data_submit > 0",
          verbatimTextOutput("data_response")
        )
      ),
      "review" = tagList(
        fileInput("code_upload", "Upload code"),
        textAreaInput("code_text", "Paste code here:", "", rows = 8),
        actionButton("review_submit", "Review"),
        conditionalPanel(
          condition = "input.review_submit > 0",
          verbatimTextOutput("review_response")
        )
      ),
      "changes" = tagList(
        dateInput("since_date", "Pick a date:"),
        actionButton("changes_submit", "Show changes"),
        conditionalPanel(
          condition = "input.changes_submit > 0",
          verbatimTextOutput("changes_response")
        )
      ),
      "hype" = tagList(
        textInput("hype_name", "What's your name?", ""),
        textInput("hype_goal", "What's up?", ""),
        actionButton("hype_submit", "Hype me up!"),
        conditionalPanel(
          condition = "input.hype_submit > 0",
          verbatimTextOutput("hype_response")
        )
      )
    )
  })
  output$guidance_response <- renderText({
    req(input$guidance_submit)
    paste("Frederick received:", input$guidance_question)
  })

  output$data_response <- renderText({
    req(input$data_submit)
    if (!is.null(input$csv_upload)) {
      paste("Frederick received uploaded file:", input$csv_upload$name)
    } else if (nzchar(input$data_question)) {
      paste("Frederick received question about data:\n", input$data_question)
    } else {
      "Please upload a CSV or ask a question about your data."
    }
  })

  output$review_response <- renderText({
    req(input$review_submit)
    if (!is.null(input$code_upload)) {
      paste("Frederick received uploaded file:", input$code_upload$name)
    } else if (nzchar(input$code_text)) {
      paste("Frederick received pasted code:\n", input$code_text)
    } else {
      "Please upload or paste your code."
    }
  })

  output$changes_response <- renderText({
    req(input$changes_submit)
    paste("Frederick will show changes since:", as.character(input$since_date))
  })

  output$hype_response <- renderText({
    req(input$hype_submit)
    greatness <- c(
      paste(input$hype_name, "you are the best!"),
      paste(input$hype_name, "the greatest statistician!"),
      paste(input$hype_name, "your skills are legendary!"),
      paste(input$hype_name, "you inspire everyone!"),
      paste(input$hype_name, "you're unstoppable!")
    )
    motivation <- c(
      "Keep going!",
      "You got this!",
      "Don't stop now!",
      "Stay awesome!",
      "The world needs your stats!"
    )
    paste(sample(greatness, 1), sample(motivation, 1), sep = "\n")
  })

  observeEvent(input$hype_submit, {
    # Track hype question in GA
    hype_input <- paste(input$hype_name, input$hype_goal, sep = " | ")
    shinyjs::runjs(
      sprintf(
        "gtag('event', 'hype_question', {'event_category': 'Chat submission', 'event_label': %s});",
        jsonlite::toJSON(hype_input)
      )
    )
  })

  observeEvent(input$reset_chat, {
    chat_clear("chat")
    chat_append("chat", "Chat has been reset. how can I help?")
  })

  observeEvent(input$chat_user_input, {
    # Track guidance question in GA
    shinyjs::runjs(
      sprintf(
        "gtag('event', 'guidance_question', {'event_category': 'Chat submission', 'event_label': %s});",
        jsonlite::toJSON(input$chat_user_input)
      )
    )

    if (
      grepl(
        "^what is the meaning of life the universe and everything$",
        tolower(gsub("[[:punct:]]", "", input$chat_user_input)),
        perl = TRUE
      )
    ) {
      chat_append(
        "chat",
        "42. But you knew that already. I hope you're happy with yourself."
      )
      return()
    }

    # Retrieve relevant excerpts, handle errors gracefully
    chunks <- tryCatch(
      {
        vs_query(
          input$chat_user_input,
          guidance_index,
          num_results = 8
        )
      },
      error = function(e) {
        chat_append(
          "chat",
          "Sorry, there was a problem, this may be because you've hit an API limit for this thread. Please reset the chat."
        )
        message("Error during vector search: ", e$message)
        return(NULL)
      }
    )

    if (is.null(chunks)) {
      return()
    }

    context_text <- paste(chunks$text, collapse = "\n\n")

    # Combine user input with context
    user_message <- paste(
      input$chat_user_input,
      "\n\nRelevant excerpts:\n",
      context_text
    )

    # Stream response from model
    stream <- chat$stream_async(user_message)

    # Return chat to user
    chat_append("chat", stream)
  })
}
