ui <- page_sidebar(
  title = "Ask Frederick",
  sidebar = sidebar(
    img(
      src = "jeeves-frederick.png",
      style = "height:300px; width:auto; display:block; margin-left:0; margin-right:auto;"
    ),
    selectInput(
      "chat_mode",
      "Choose chat mode:",
      choices = c(
        "Guidance search" = "guidance",
        "Data interrogator" = "data_interrogator",
        "Code review" = "review",
        "EES changes" = "changes",
        "Hype me up" = "hype"
      )
    )
  ),

  # Logo
  #conditionalPanel(
  #  condition = "input.chat_mode == 'guidance'",
  #  img(
  #    src = "guidance-frederick.png",
  #    style = "height:300px; width:auto; display:block; margin-left:0; margin-right:auto;"
  #  )
  #),
  conditionalPanel(
    condition = "input.chat_mode == 'data_interrogator'",
    img(
      src = "data-interrogator-frederick.png",
      style = "height:300px; width:auto; display:block; margin-left:0; margin-right:auto;"
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'review'",
    img(
      src = "code-frederick.png",
      style = "height:300px; width:auto; display:block; margin-left:0; margin-right:auto;"
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'changes'",
    img(
      src = "changes-frederick.png",
      style = "height:300px; width:auto; display:block; margin-left:0; margin-right:auto;"
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'hype'",
    img(
      src = "hype-frederick.png",
      style = "height:300px; width:auto; display:block; margin-left:0; margin-right:auto;"
    )
  ),

  # Description
  conditionalPanel(
    condition = "input.chat_mode == 'data_interrogator'",
    p("Frederick will analyse your dataset and answer your questions about it.")
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'review'",
    p("Frederick will review your code and provide feedback.")
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'changes'",
    p(
      "Frederick will summarise any changes and improvements to Explore education statistics (EES) since the date you specify."
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'hype'",
    p(
      "Frederick will give you a personalised hype message to boost your motivation!"
    )
  ),

  # Controls
  conditionalPanel(
    condition = "input.chat_mode == 'guidance'",
    bslib::card(
      chat_ui(
        id = "chat",
        messages = "Hey hey hey! I will search available guidance from the Analysts' Guide and Statistics HoP Hub to provide the answers to your questions. How can I help?",
        icon_assistant = img(
          src = "guidance-frederick.png",
          style = "height:30px; width:auto;"
        )
      ),
      full_screen = TRUE,
      fillable = TRUE,
      style = "width: 100%; height: 100%;"
    ),
    actionButton("reset_chat", "Reset Chat"),
    div(
      style = "background-color: #f8f9fa; border-left: 4px solid #0072B2; padding: 12px;",
      strong("Note:"),
      "Responses are generated by AI based on the Analysts' Guide and HoP hub materials. Please verify any answers using the",
      tags$a(
        href = "https://rsconnect/rsc/hop-guidance/",
        "HoP Hub",
        target = "_blank"
      ),
      "or the",
      tags$a(
        href = "https://dfe-analytical-services.github.io/analysts-guide/",
        "Analysts' Guide",
        target = "_blank"
      ),
      "websites."
    ),
    div(
      style = "background-color: #f8f9fa; border-left: 4px solid #0072B2; padding: 12px; margin-bottom: 16px;",
      strong("Note:"),
      "The app may crash after too many questions, if this happens, please refresh the page to reset the chat."
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'data_interrogator'",
    tagList(
      fileInput("csv_upload", "Upload CSV file"),
      textInput("data_question", "Ask about your data:", ""),
      actionButton("data_submit", "Ask")
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'review'",
    tagList(
      fileInput("code_upload", "Upload code"),
      textAreaInput("code_text", "Paste code here:", "", rows = 8),
      actionButton("review_submit", "Review")
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'changes'",
    tagList(
      dateInput("since_date", "Pick a date:"),
      actionButton("changes_submit", "Show changes")
    )
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'hype'",
    tagList(
      textInput("hype_name", "What's your name?", ""),
      textInput("hype_goal", "What's up?", ""),
      actionButton("hype_submit", "Hype me up!")
    )
  ),

  # Response
  conditionalPanel(
    condition = "input.chat_mode == 'data_interrogator' && input.data_submit > 0",
    verbatimTextOutput("data_response")
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'review' && input.review_submit > 0",
    verbatimTextOutput("review_response")
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'changes' && input.changes_submit > 0",
    verbatimTextOutput("changes_response")
  ),
  conditionalPanel(
    condition = "input.chat_mode == 'hype' && input.hype_submit > 0",
    verbatimTextOutput("hype_response")
  )
)
